version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container-api
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
